# Generated by Django 6.0.6 on 2026-07-24 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessment', '0001_initial'),
        ('skill', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmentskill',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_skills', to='assessment.assessment'),
        ),
        migrations.AddField(
            model_name='assessmentskill',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmentskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_assessments', to='skill.skill'),
        ),
        migrations.AddField(
            model_name='assessmentskill',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentassessment',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_assessments', to='assessment.assessment'),
        ),
        migrations.AddField(
            model_name='studentassessment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentassessment',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentassessment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentskillresult',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentskillresult',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_skill_results', to='skill.skill'),
        ),
        migrations.AddField(
            model_name='studentskillresult',
            name='student_assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_results', to='assessment.studentassessment'),
        ),
        migrations.AddField(
            model_name='studentskillresult',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['assessment_type'], name='idx_assessment_type'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['course'], name='idx_assessment_course'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['target_level'], name='idx_assessment_level'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['assessment_phase'], name='idx_assessment_phase'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['is_active'], name='idx_assessment_active'),
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('title',), name='unique_active_assessment_title'),
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.CheckConstraint(condition=models.Q(('passing_score__gte', 0), ('passing_score__lte', 100)), name='valid_passing_score'),
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.CheckConstraint(condition=models.Q(('max_attempts__gte', 1)), name='valid_max_attempts'),
        ),
        migrations.AddConstraint(
            model_name='assessmentskill',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('assessment', 'skill'), name='unique_active_assessment_skill'),
        ),
        migrations.AddConstraint(
            model_name='studentassessment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'in_progress')), fields=('student', 'assessment'), name='unique_in_progress_assessment'),
        ),
        migrations.AddConstraint(
            model_name='studentassessment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'completed')), fields=('student', 'assessment', 'attempt_number'), name='unique_student_assessment_attempt'),
        ),
        migrations.AddConstraint(
            model_name='studentskillresult',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('student_assessment', 'skill'), name='unique_active_student_skill_result'),
        ),
    ]
