# Generated by Django 6.0.6 on 2026-07-15 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_coursebatch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursebatch',
            name='days',
        ),
        migrations.RemoveField(
            model_name='coursebatch',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='coursebatch',
            name='start_time',
        ),
        migrations.AddField(
            model_name='coursebatch',
            name='schedule',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='coursebatch',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='active', max_length=20),
        ),
    ]
