# Generated by Django 6.0.6 on 2026-07-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_remove_coursebatch_days_remove_coursebatch_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='prefix',
            field=models.CharField(default='CS', max_length=20),
        ),
        migrations.AlterField(
            model_name='coursebatch',
            name='batch_code',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
