# Generated by Django 6.0.6 on 2026-07-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_prefix_alter_coursebatch_batch_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='prefix',
            field=models.CharField(max_length=20),
        ),
    ]
