# Generated by Django 6.0.6 on 2026-07-21 11:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_coursebatch_mentor_alter_course_prefix_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursebatch',
            options={},
        ),
        migrations.AlterField(
            model_name='coursebatch',
            name='batch_code',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddConstraint(
            model_name='coursebatch',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('batch_code',), name='unique_batch_code_not_deleted'),
        ),
    ]
