# Generated by Django 6.0.6 on 2026-07-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('student', 'Student'), ('mentor', 'Mentor'), ('concenllor', 'Concenllor')], default='staff', max_length=20),
        ),
    ]
