# Generated by Django 6.0.6 on 2026-07-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('student', 'Student'), ('mentor', 'Mentor'), ('counselor', 'Counselor')], default='student', max_length=20),
        ),
    ]
