# Generated by Django 6.0.6 on 2026-07-20 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_counselorprofile_mentorprofile_studentprofile_and_more'),
        ('career', '0001_initial'),
        ('skill', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='career_goals',
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='skills',
            field=models.ManyToManyField(related_name='mentors_skill', to='skill.skill'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='career',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profiles', to='career.career'),
        ),
    ]
